### ISSUE TITLE
Executable for arm64 created by build pipeline does not work

### ISSUE THREAD

**Issue by triumphvalley** [reveal-editor/reveal-editor#20]
The executable for arm64 does not work on my mac. Here's a screenshot of the error message:
![Bildschirm­foto 2023-05-15 um 08 21 32](https://github.com/reveal-editor/reveal-editor/assets/76257277/d34736a5-817a-4fc7-9bb4-d542f777f67f)

**Comment by simonschuhmacher** [comment]
This should be fixed with #22, could you try `v0.0.1-alpha.9` or `v0.0.1-alpha.8`?
