### ISSUE TITLE
Export HTML Bundle Not Working in Packaged Version

### ISSUE THREAD

**Issue by simonschuhmacher** [reveal-editor/reveal-editor#32]
- Export to a HTML bundle is not working with release produced by CI/CD
- Content of `presentation.html` is just `@@content@@`

**Comment by simonschuhmacher** [comment]
It seems that the presentation file is not written, just the template files are copied (tested with `v0.0.1-alpha.13`)

**Comment by simonschuhmacher** [comment]
It just turned out the issue occurs when images cannot be resolved. If images can be resolved, it works.

**Comment by triumphvalley** [comment]
We just need better error handling #47
